# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
    debug:
      desc: '選擇需要進行的debug動作'
      cmd: "{{ .CHOOSE }} ./scripts/bin/debug.sh"
    
    log:
      desc: "📜 查看容器各種狀態"
      cmd: "{{ .CHOOSE }} ./scripts/bin/kubectl-log.sh"
    
    log-label:
      desc: "查看各種labels"
      silent: true
      cmd: "{{ .CHOOSE }} scripts/bin/status/kubectl-labels.sh"
    check-image:
      desc: "檢查本地registry image"
      silent: true
      cmds:
        - curl -s http://localhost:5000/v2/_catalog | jq .
