coreDnsCustom:
  enabled: true
  localDomains:
    - registry.local
    - registry-ui.local
    - forgejo.local
    - argo.local
    - baoyan-dev.local
    - grafana.local
    - temporal.local
    - portainer.local
    - sql.local
    - baoyan-epic.local

