# 放在 server 區塊外面
upstream service_app {
    server nginx-service:80;
    keepalive 32; # 保持 32 個閒置長連線，不隨便關閉
}

server {
    listen 80 ;   # 指定為預設 server
    server_name temporal.local grafana.local;

    # 信任來自宿主機網關的連線，已包含 Docker 預設的內部網段，也包含 K8s 常用的 Pod 網段與 Service 網段
    set_real_ip_from  10.0.0.0/8;
    
    # 2. 指定從 X-Forwarded-For 讀取真實 IP
    real_ip_header    X-Forwarded-For;
    
    # 3. 遞迴搜尋標頭，直到找到非信任來源的 IP
    real_ip_recursive on;
    # 定義後端目標 (第三層)
    
    resolver kube-dns.kube-system.svc.cluster.local valid=30s;
    set $upstream_target http://service_app;

    location / {
        proxy_pass $upstream_target;
        # 處理 WebSocket 升級
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto; # 延續第一層傳來的 https
    }
}