[PHP]
; 核心行為
; 名稱之所以叫做custom-php.ini 是保證能夠讀到custom-php.ini 因為linux 會先讀取php.ini 才會讀其他的ini
short_open_tag = On
max_execution_time = 120
memory_limit = 1024M
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors = Off
log_errors = On
error_log = /proc/1/fd/2  ; 輸出到 container stdout
display_startup_errors = Off
date.timezone = Asia/Taipei

; 文件上傳
file_uploads = On
upload_max_filesize = 50M
post_max_size = 100M
session.save_handler = redis
session.save_path = "tcp://redis:6379"

; 效能與相容性
cgi.fix_pathinfo = 1
realpath_cache_size = 4096K
realpath_cache_ttl = 600
opcache.enable = 1
opcache.memory_consumption = 256
opcache.validate_timestamps = 0  ; production 用